spring.application.name=backend
spring.config.import=optional:file:./env/local.env[.properties],optional:file:./backend/env/local.env[.properties]
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pc2_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
